[package]
name = "strafe"
version = "0.1.0"
authors = ["jasper"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest="0.9.18"
chrono="0.4"
html5ever = "*"
